apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  labels:
    app: moodle
spec:
  selector:
    matchLabels:
      app: moodle
  replicas: 1
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: bitnami/moodle:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MOODLE_DATABASE_USER
          value: "admin"
        - name: MOODLE_DATABASE_PASSWORD
          value: "admin1234"
        - name: MOODLE_DATABASE_NAME
          value: "bitnami_moodle"
        - name: MOODLE_DATABASE_HOST
          value: "endpoint"
        volumeMounts:
        - name: moodle-storage
          mountPath: /bitnami/moodle
      volumes:
      - name: moodle-storage
        persistentVolumeClaim:
          claimName: moodle-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app: moodle
