aws_region                  = "us-east-1"
cluster_name                = "moodle-cluster"
vpc_cidr                    = "10.0.0.0/16"
public_subnets              = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnets             = ["10.0.3.0/24", "10.0.4.0/24"]
moodle_admin_user           = "admin"
moodle_admin_password       = "my-moodle-admin-password"
moodle_admin_email          = "admin@commoncloud.tech"
mariadb_root_password       = "my-mariadb-root-password"
mariadb_user                = "bn_moodle"
mariadb_password            = "my-mariadb-password"
mariadb_database            = "bitnami_moodle"
domain_name                 = "commoncloud.tech"
